[project]
name = "news-crawler"
version = "0.1.0"
description = "Crawl market news"
authors = [
    { name="Yoiq S Rambadian", email="yoiqrambadian@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=5.3.2",
    "requests>=2.32.3",
]
